ignore:
  - "app/src/main/java/com/coconutbmp/leash/MainActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/AddBudgetDialogue.java"
  - "app/src/main/java/com/coconutbmp/leash/AddIncomeActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/AddLiabilityActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/AddLoanDetailsFragment.java"
  - "app/src/main/java/com/coconutbmp/leash/AddToBudgetDialogue.java"
  - "app/src/main/java/com/coconutbmp/leash/AddTransactionsActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/BudgetListLayout.java"
  - "app/src/main/java/com/coconutbmp/leash/ProfileActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/HomeActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/BudgetActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/AddTransactionActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/LiabilityDetailsActivity.java"
  - "app/src/main/java/com/coconutbmp/leash/AddRecurringPaymentFragment.java"
  - "app/src/main/java/com/coconutbmp/leash/LiabilityHistoryLayout.java"
  - "app/src/main/java/com/coconutbmp/leash/LiabilityBrief.java"
  - "app/src/main/java/com/coconutbmp/leash/IncomeBrief.java"
  - "app/src/main/java/com/coconutbmp/leash/TransactionBrief.java"
  - "app/src/main/java/com/coconutbmp/leash/BudgetBrief.java"
  - "app/src/main/java/com/coconutbmp/leash/EditProfileDialog.java"
  - "app/src/main/java/com/coconutbmp/leash/ManageBudgetDialog.java"
  - "app/src/main/java/com/coconutbmp/leash/SummaryFragment.java"
  - "app/src/main/java/com/coconutbmp/leash/BudgetComponentFragment.java"
